/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebcamRouteImport } from './routes/webcam'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as PessoasRouteImport } from './routes/pessoas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const WebcamRoute = WebcamRouteImport.update({
  id: '/webcam',
  path: '/webcam',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasRoute = PessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/pessoas': typeof PessoasRoute
  '/upload': typeof UploadRoute
  '/webcam': typeof WebcamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/pessoas': typeof PessoasRoute
  '/upload': typeof UploadRoute
  '/webcam': typeof WebcamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/pessoas': typeof PessoasRoute
  '/upload': typeof UploadRoute
  '/webcam': typeof WebcamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/pessoas' | '/upload' | '/webcam'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/pessoas' | '/upload' | '/webcam'
  id: '__root__' | '/' | '/cadastro' | '/pessoas' | '/upload' | '/webcam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  PessoasRoute: typeof PessoasRoute
  UploadRoute: typeof UploadRoute
  WebcamRoute: typeof WebcamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webcam': {
      id: '/webcam'
      path: '/webcam'
      fullPath: '/webcam'
      preLoaderRoute: typeof WebcamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas': {
      id: '/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  PessoasRoute: PessoasRoute,
  UploadRoute: UploadRoute,
  WebcamRoute: WebcamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
